//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.EventoUsuarios = new HashSet<EventoUsuario>();
        }
    
        public int IDEvento { get; set; }
        public string Titulo { get; set; }
        public string Comentarios { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public int IDEstado { get; set; }
        public int IDUsuario { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<EventoUsuario> EventoUsuarios { get; set; }
    }
}
