//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioHorario
    {
        public int IDUsuarioHorario { get; set; }
        public int IDUsuario { get; set; }
        public int IDDia { get; set; }
        public int Hour_1 { get; set; }
        public int Hour_2 { get; set; }
        public int Hour_3 { get; set; }
        public int Hour_4 { get; set; }
        public int Hour_5 { get; set; }
        public int Hour_6 { get; set; }
        public int Hour_7 { get; set; }
        public int Hour_8 { get; set; }
        public int Hour_9 { get; set; }
        public int Hour_10 { get; set; }
        public int Hour_11 { get; set; }
        public int Hour_12 { get; set; }
        public int Hour_13 { get; set; }
        public int Hour_14 { get; set; }
        public int Hour_15 { get; set; }
        public int Hour_16 { get; set; }
        public int Hour_17 { get; set; }
        public int Hour_18 { get; set; }
        public int Hour_19 { get; set; }
        public int Hour_20 { get; set; }
        public int Hour_21 { get; set; }
        public int Hour_22 { get; set; }
        public int Hour_23 { get; set; }
        public int Hour_24 { get; set; }
    
        public virtual Dia Dia { get; set; }
        public virtual Disponibilidad Disponibilidad { get; set; }
        public virtual Disponibilidad Disponibilidad1 { get; set; }
        public virtual Disponibilidad Disponibilidad2 { get; set; }
        public virtual Disponibilidad Disponibilidad3 { get; set; }
        public virtual Disponibilidad Disponibilidad4 { get; set; }
        public virtual Disponibilidad Disponibilidad5 { get; set; }
        public virtual Disponibilidad Disponibilidad6 { get; set; }
        public virtual Disponibilidad Disponibilidad7 { get; set; }
        public virtual Disponibilidad Disponibilidad8 { get; set; }
        public virtual Disponibilidad Disponibilidad9 { get; set; }
        public virtual Disponibilidad Disponibilidad10 { get; set; }
        public virtual Disponibilidad Disponibilidad11 { get; set; }
        public virtual Disponibilidad Disponibilidad12 { get; set; }
        public virtual Disponibilidad Disponibilidad13 { get; set; }
        public virtual Disponibilidad Disponibilidad14 { get; set; }
        public virtual Disponibilidad Disponibilidad15 { get; set; }
        public virtual Disponibilidad Disponibilidad16 { get; set; }
        public virtual Disponibilidad Disponibilidad17 { get; set; }
        public virtual Disponibilidad Disponibilidad18 { get; set; }
        public virtual Disponibilidad Disponibilidad19 { get; set; }
        public virtual Disponibilidad Disponibilidad20 { get; set; }
        public virtual Disponibilidad Disponibilidad21 { get; set; }
        public virtual Disponibilidad Disponibilidad22 { get; set; }
        public virtual Disponibilidad Disponibilidad23 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
