//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Eventoes = new HashSet<Evento>();
            this.EventoUsuarios = new HashSet<EventoUsuario>();
            this.UsuarioHorarios = new HashSet<UsuarioHorario>();
        }
    
        public int IDUsuario { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoUsuario> EventoUsuarios { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios { get; set; }
    }
}
