//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad
    {
        public Disponibilidad()
        {
            this.EventoUsuarioHorarios = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios1 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios2 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios3 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios4 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios5 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios6 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios7 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios8 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios9 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios10 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios11 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios12 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios13 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios14 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios15 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios16 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios17 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios18 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios19 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios20 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios21 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios22 = new HashSet<EventoUsuarioHorario>();
            this.EventoUsuarioHorarios23 = new HashSet<EventoUsuarioHorario>();
            this.UsuarioHorarios = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios1 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios2 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios3 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios4 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios5 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios6 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios7 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios8 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios9 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios10 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios11 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios12 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios13 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios14 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios15 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios16 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios17 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios18 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios19 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios20 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios21 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios22 = new HashSet<UsuarioHorario>();
            this.UsuarioHorarios23 = new HashSet<UsuarioHorario>();
        }
    
        public int IDDisponibilidad { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios1 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios2 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios3 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios4 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios5 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios6 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios7 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios8 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios9 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios10 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios11 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios12 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios13 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios14 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios15 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios16 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios17 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios18 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios19 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios20 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios21 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios22 { get; set; }
        public virtual ICollection<EventoUsuarioHorario> EventoUsuarioHorarios23 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios1 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios2 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios3 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios4 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios5 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios6 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios7 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios8 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios9 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios10 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios11 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios12 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios13 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios14 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios15 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios16 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios17 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios18 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios19 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios20 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios21 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios22 { get; set; }
        public virtual ICollection<UsuarioHorario> UsuarioHorarios23 { get; set; }
    }
}
